(function(g){var window=this;'use strict';var deb=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},eeb=function(a){return g.OK(a)?g.rJ(a.experiments,"web_player_caption_language_preference_stickiness_duration"):0},feb=function(a,b){var c=new g.iL;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;a.xtags&&(c.xtags=a.xtags);a.captionId&&(c.captionId=a.captionId);return c},geb=function(a,b){var c,d,e;
return g.A(function(f){if(1==f.j)return c=a+"|"+b,g.y(f,g.iB(),2);if(3!=f.j){d=f.u;if(!d)throw g.GA("gct");return g.y(f,g.$L(d),3)}e=f.u;return f.return(e.get("captions",c))})},heb=function(a,b,c){geb(a,b).then(function(d){d&&c(d.trackData,new g.iL(d.metadata))})},keb=function(a){if(!ieb.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(jeb,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},leb=function(){return g.Tz("yt-player-caption-display-settings")},f5=function(){this.segments=[]},meb=function(a,b){var c=g.Ob(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.zb(a.segments,c),g.zb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.Jb(a.segments,c,0,b),g.Jb(a.segments,c+1,0,b)))},neb=function(a,b,c,d,e,f){g.E.call(this);
this.policy=a;this.player=b;this.ea=c;this.onLoadCallback=d;this.D=e;this.T=f;this.C=new f5;this.I=-1;this.B=this.u=this.j=null;this.J=new g.Gp(this.rV,1E3,this);this.events=new g.XH(this);g.I(this,this.J);g.I(this,this.events);this.events.S(b,"SEEK_COMPLETE",this.rz);this.rz();this.rV()},oeb=function(a){return a.j&&a.j.B?a.j.B+a.player.Gd()<a.player.getCurrentTime():!1},peb=function(a,b){var c=g.nH(b,a.policy,{}).bf(),d={format:"RAW",
withCredentials:!0};if(a.policy.Aa){d.method="POST";var e=b.Gs(),f=(0,g.LX)([120,0]);e&&g.KL(e,g.JKa);d.postBody=f}a.D&&(d.responseType="arraybuffer");a.B=g.Oy(c,d,3,100).then(function(h){a:{h=h.xhr;a.isDisposed();if(a.u){var l=!(a.D?h.response:h.responseText)||400<=h.status,m=g.kua(h);if(m){h=g.nH(a.u,a.policy,{});a.u.Ek(h,m);peb(a,a.u);break a}if(l)a.player.xa("capfail",{status:h.status});else if(a.player.Ph().gi("fcb_r"),m=a.u.ib[0].Na,null!=a.onLoadCallback&&a.I!==m){l=a.u.ib[0];if(a.D)a.onLoadCallback(h.response,
1E3*(l.startTime+a.player.Gd()));else a.onLoadCallback(h.responseText,1E3*(l.startTime+a.player.Gd()));a.I=m}}a.u=null;a.B=null}}).dk(function(h){a.u=null;
a.B=null;var l;a.player.xa("capfail",{status:null==(l=h.xhr)?void 0:l.status})});
a.u=b;meb(a.C,a.u.ib[0].Na)},g5=function(a,b){g.wT.call(this,b.V());
this.u=a;this.F=b;this.B=null;this.D=!1;this.I=g.QK(this.F.V())&&!this.u.isManifestless},reb=function(a,b){var c=[],d;
for(d in a.u.j)if(a.u.j.hasOwnProperty(d)){var e=a.u.j[d];if(g.KKa(e,b||null)){var f=e.info.id,h=f,l="."+f,m="",n="",p="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind,a.F.V().K("html5_expose_xtags_through_caption_track")&&(n=e.xtags),p=e.id;else{e=f;var q=g.ecb.get(e);null==q&&(q=qeb[e]||qeb[e.replace(/-/g,"_")],g.ecb.set(e,q));h=q||h}c.push(new g.iL({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m,xtags:n,captionId:p}))}}return c},
seb=function(a,b){return null!=b&&b in a.u.j?a.u.j[b]:null},teb=function(a,b,c){var d=[],e;
for(e in a.u.j)if(a.u.j.hasOwnProperty(e)){var f=a.u.j[e];if(g.KKa(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},veb=function(){var a=void 0;
a=void 0===a?{}:a;var b="suggest_correction"in ueb?ueb.suggest_correction:"Edit caption";b=b||"";var c={},d;for(d in a){c.uA=d;var e=function(f){return function(){return String(a[f.uA])}}(c);
b=b.replace(new RegExp("\\$\\{"+c.uA+"\\}","gi"),e);b=b.replace(new RegExp("\\$"+c.uA,"gi"),e);c={uA:c.uA}}return b},h5=function(a,b,c,d,e,f,h,l,m,n){var p={};
Object.assign(p,b);Object.assign(p,a.params);Object.assign(p,c);var q={};Object.assign(q,b.Fe);a.params.Fe&&Object.assign(q,a.params.Fe);Object.assign(q,c.Fe);p.Fe=q;var t=1===p.di,w=[{G:"span",N:"captions-text",X:{style:"word-wrap: normal; display: block;"}}],z,C,G;(l=l.ob("caption_edit_on_hover")&&(null==(z=n.getVideoData().getPlayerResponse())?void 0:null==(C=z.captions)?void 0:null==(G=C.playerCaptionsTracklistRenderer)?void 0:G.openTranscriptCommand))&&w.unshift({G:"button",N:"caption-edit",
X:{tabindex:"0","aria-label":veb()},W:[{G:"svg",X:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},W:[{G:"path",X:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.V.call(this,{G:"div",N:"caption-window",X:{id:"caption-window-"+a.id,dir:t?"rtl":"ltr",tabindex:"0",lang:p.lang},W:w});var O=this;this.I=[];this.Ga=!1;this.u=a;this.Ma=
this.Ka=null;this.playerWidth=f;this.playerHeight=h;this.J=null;this.maxWidth=.96*f;this.Za=.96*h;this.j=p;this.Mc=c;this.ya=b;this.C=this.Da("captions-text");this.Dc=""!==this.C.style.getPropertyValue("box-decoration-break")||""!==this.C.style.getPropertyValue("-webkit-box-decoration-break");this.Pa=web(d,e,f,h);this.kd=m;l&&(this.D=this.Da("caption-edit"),this.S(this.D,"click",function(){O.kd()}));
this.type=0;this.jb=this.Pa*xeb(q);a=new g.aT(this.element,!0);g.I(this,a);a.subscribe("dragstart",this.YZ,this);a.subscribe("dragmove",this.XZ,this);a.subscribe("dragend",this.WZ,this);this.ub=this.qb=this.Vb=this.Gb=0;a="";this.j.windowOpacity&&(a=keb(this.j.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");b={"background-color":a,display:!1===this.j.isVisible?"none":"","text-align":yeb[this.j.textAlign]};this.Dc&&(b["border-radius"]=a?this.jb/8+"px":"");(this.B=2===this.u.params.di||
3===this.u.params.di)&&zeb(this,this.element);g.Pm(this.element,b);switch(this.j.Cl){case 0:case 1:case 2:g.Op(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.Op(this.element,"ytp-caption-window-bottom")}},zeb=function(a,b){var c="vertical-rl";
1===a.j.GP&&(c="vertical-lr");g.Ve&&(c="vertical-lr"===c?"tb-lr":"tb-rl");g.Pm(b,"-o-writing-mode",c);g.Pm(b,"-webkit-writing-mode",c);g.Pm(b,"writing-mode",c);g.Pm(b,"text-orientation","upright");g.Op(b,"ytp-vertical-caption");3===a.u.params.di&&(g.Pm(b,"text-orientation",""),g.Pm(b,"transform","rotate(180deg)"))},xeb=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},Aeb=function(a,b){var c={},d=b.background?b.background:a.j.Fe.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.j.Fe.backgroundOpacity;d=keb(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Dc&&(c["box-decoration-break"]="clone",c["border-radius"]=a.jb/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Pa*xeb(b)+"px";d=1;e=b.color||a.j.Fe.color;if(b.color||null!=b.textOpacity)e=keb(e),d=null==b.textOpacity?a.j.Fe.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.NK&&(h=e=b.NK);var l=a.Pa/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.az()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.j.Fe.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.italic&&(c["font-style"]=
"italic");b.underline&&(c["text-decoration"]="underline");b.E4&&(c.visibility="hidden");1===b.IU&&a.B&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.SK||g.EA,3===a.u.params.di?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Gn||2===b.Gn||3===b.Gn||4===b.Gn||5===b.Gn)if(g.SK)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Gn){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},Beb=function(a){a.J=g.df("SPAN");
g.Pm(a.J,{display:"block"});g.Op(a.J,"caption-visual-line");a.C.appendChild(a.J)},Ceb=function(a,b){var c=g.df("SPAN");
g.Pm(c,{display:"inline-block","white-space":"pre-wrap"});g.Pm(c,Aeb(a,b));c.classList.add("ytp-caption-segment");a.J.appendChild(c);c.previousElementSibling&&(g.Pm(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Pm(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},Deb=function(a,b,c){a.Ga=a.Ga||!!c;
var d={};Object.assign(d,a.j.Fe);Object.assign(d,c||b.j);Object.assign(d,a.Mc.Fe);(c=!a.J)&&Beb(a);for(var e=a.Ka&&a.Ma&&g.id(d,a.Ma)?a.Ka:Ceb(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(Beb(a),e=Ceb(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.ef(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.SK||!g.Rm(n.children[2],"text-emphasis")||(m=a.B?"padding-right":"padding-top",g.Rm(n.children[2],"text-emphasis-position")&&(m=
a.B?"padding-left":"padding-bottom"),g.Nc?g.Pm(e,m,"1em"):g.Pm(e,m,"0.5em")))}a.Ma=d;a.Ka=e;a.I.push(b)},web=function(a,b,c,d){var e=b/360*16;
b>=a&&(a=640,d>1.3*c&&(a=480),e=c/a*16);return e},i5=function(a,b,c,d){g.wT.call(this,a);
this.videoData=b;this.audioTrack=c;this.Va=d;this.C=b.KK},j5=function(a,b,c,d,e,f,h,l,m,n){h5.call(this,a,b,c,d,e,f,h,l,m,n);
this.type=1},k5=function(a,b,c,d,e,f,h,l,m,n){h5.call(this,a,b,c,d,e,f,h,l,m,n);
var p=this;this.type=2;this.T=[];this.oa=this.Z=this.Xa=0;this.Aa=NaN;this.lc=0;this.Ic=null;this.bb=new g.Gp(this.C7,433,this);this.D&&(n.tb(this.D,this,167342),this.S(this.D,"click",function(){n.rb(p.D)}),a=new g.aT(this.element,!0),g.I(this,a),a.subscribe("hoverstart",function(){n.Wa(p.D,!0)},this));
g.Op(this.element,"ytp-caption-window-rollup");g.I(this,this.bb);g.Pm(this.element,"overflow","hidden")},Eeb=function(a,b){if(!b)return"";
a.B&&1!==a.u.params.GP&&(b*=-1);return"translate"+(a.B?"X":"Y")+"("+b+"px)"},Feb=function(a){a.T=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.u.params.Sq,c=0,d=0,e=a.T.length-1;c<b&&-1<e;){var f=a.T[e];d+=a.B?f.offsetWidth:f.offsetHeight;c++;e--}a.T.length<b&&(d*=b/a.T.length);a.Z=d;b=Math;c=b.max;isNaN(a.Aa)&&((d=a.j.Or)?(e=g.df("SPAN"),g.qf(e,"\u2013".repeat(d)),g.Pm(e,Aeb(a,a.j.Fe)),a.C.appendChild(e),a.Aa=e.offsetWidth,a.C.removeChild(e)):a.Aa=0);d=a.C;a.oa=c.call(b,a.Aa,a.lc,(a.B?d.offsetHeight:d.offsetWidth)+1)},Geb=function(a,b){Feb(a);
var c=a.T.reduce(function(e,f){return(a.B?f.offsetWidth:f.offsetHeight)+e},0);
c=a.Z-c;if(c!==a.Xa){var d=0<c&&0===a.Xa;b||isNaN(c)||d||(g.Op(a.element,"ytp-rollup-mode"),g.Hp(a.bb));g.Pm(a.C,"transform",Eeb(a,c));a.Xa=c}Feb(a)},l5=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.bE.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=h},m5=function(a,b,c,d,e){g.bE.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},Heb=function(a){var b="_"+n5++;
return new m5(0,0x8000000000000,0,b,a)},Jeb=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.Rf){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=Ieb(l.textContent,n.textContent,p.textContent,f.textContent,h);return new l5(a,b,e,c,l,d,m)}switch(m.Rf){case 9:case 10:m.Gn=1;break;case 11:m.Gn=2;break;case 12:m.Gn=3;break;case 13:m.Gn=4;break;case 14:m.Gn=5}return new l5(a,b,e,c,l.textContent||"",d,m)},Ieb=function(a,b,c,d,e){var f=g.az(),h=
f?g.df("DIV"):g.df("RUBY"),l=g.df("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.df("DIV"):g.df("RP");a.textContent=b;h.appendChild(a);b=f?g.df("DIV"):g.df("RT");b.textContent=c;h.appendChild(b);c=e.Rf;if(10===c||11===c||12===c||13===c||14===c)if(g.Pm(b,"text-emphasis-style","filled circle"),g.Pm(b,"text-emphasis-color","currentcolor"),g.Pm(b,"webkit-text-emphasis","filled circle"),11===e.Rf||13===e.Rf)g.Pm(b,"webkit-text-emphasis-position","under left"),g.Pm(b,"text-emphasis-position","under left");c=!0;if(4===e.Rf||7===e.Rf||12===e.Rf||
14===e.Rf)g.Pm(h,"ruby-position","over"),g.Pm(h,"-webkit-ruby-position","before");else if(5===e.Rf||6===e.Rf||11===e.Rf||13===e.Rf)g.Pm(h,"ruby-position","under"),g.Pm(h,"-webkit-ruby-position","after"),c=!1;e=f?g.df("DIV"):g.df("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.Pm(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.Pm(f,"display","none"),f=f.nextElementSibling,g.Pm(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Pm(h.lastElementChild,"display","none"),d?(g.Pm(h,"padding-top","0.6em"),g.Pm(f,"top","0")):(g.Pm(h,"padding-bottom","0.6em"),g.Pm(f,"bottom","0")));return h},o5=function(){g.E.apply(this,arguments)},p5=function(a){o5.call(this);
this.C=a;this.pens={};this.T={};this.ea={};this.D="_"+n5++;this.J={};this.B=this.j=null;this.I=!0},q5=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},r5=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},s5=function(a,b){a=q5(a,b);
return void 0!==a?a:null},u5=function(a,b){a=a.getAttribute(b);
if(null!=a)return t5.test(a),a},Keb=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.ea[d]:a.C);a=s5(b,"mh");null!=a&&(c.jz=a);a=s5(b,"ju");null!=a&&(c.textAlign=a);a=s5(b,"pd");null!=a&&(c.di=a);a=s5(b,"sd");null!=a&&(c.GP=a);a=u5(b,"wfc");null!=a&&(c.windowColor=a);b=q5(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},Leb=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.T[d]);a=s5(b,"ap");null!=a&&(c.Cl=a);a=q5(b,"cc");null!=a&&(c.Or=a);a=q5(b,"ah");null!=a&&(c.Kj=a);a=q5(b,"rc");null!=a&&(c.Sq=a);b=q5(b,"av");null!=b&&(c.Hn=b);return c},Meb=function(a,b,c,d){var e={};
Object.assign(e,Leb(a,b));Object.assign(e,Keb(a,b));d?g.id(e,a.C)?(d=a.D,e=a.C):d="_"+n5++:d=b.getAttribute("id")||"_"+n5++;a=q5(b,"t")+c;b=q5(b,"d")||0x8000000000000;if(2===e.di||3===e.di)c=e.Sq,e.Sq=e.Or,e.Or=c;return new m5(a,b,0,d,e)},v5=function(a){o5.call(this);
this.I=a;this.j=new Map;this.C=new Map;this.D=new Map;this.B=new Map},w5=function(a){a=g.pe(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},Neb=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.D.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.Sq=a);b=b.ccColCount;void 0!==b&&(f.Or=b);if(2===f.di||3===f.di)b=f.Sq,f.Sq=f.Or,f.Or=b;return new m5(c,d,0,e,f)},Peb=function(){this.B=this.time=this.mode=this.u=0;
this.C=new Oeb(this);this.D=new Oeb(this);this.j=[];this.clear()},Reb=function(a,b,c){if(255===a&&255===b||!a&&!b)return{Bu:a,
Kr:b,result:0};a=Qeb[a];b=Qeb[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.Ge()&&c.Kr===d;if(d)return{Bu:a,Kr:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Bu:a,Kr:b,result:2};return{Bu:a,Kr:b,result:3}},Teb=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.B&&a.reset(),a.C.u.clear(),a.D.u.clear()):(a.B=0,Seb(a.C,b,c,d))},Ueb=function(a,b){a.j.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.v(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?Teb(a,d.RS,d.SS,b):1===d.type&&a.u&496&&Seb(a.D,d.RS,d.SS,b);a.j.length=0},x5=function(){this.type=0},y5=function(){this.state=this.Kr=this.Bu=0},Veb=function(){this.timestamp=this.j=0},z5=function(a){this.D=a;
this.B=[];this.j=this.u=this.row=0;this.style=new x5;for(a=this.C=0;15>=a;a++){this.B[a]=[];for(var b=0;32>=b;b++)this.B[a][b]=new Veb}},A5=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var q=a.B[m][p];
if(0!==q.j){0===c&&(c=m,d=p);n=String.fromCharCode(q.j);var t=q.timestamp;t<e&&(e=t);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===q.j||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.C(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.B[h][m],q=p.j,0!==q&&(0===c&&(c=h,d=m),n=String.fromCharCode(q),t=p.timestamp,t<=e&&(e=t),l+=n,p.reset()),32===m||0===q)l&&b.C(c,d,e,f,l),e=f,l="",d=c=0},$eb=function(a,b){switch(a){case 0:return Web[(b&127)-32];
case 1:return Xeb[b&15];case 2:return Yeb[b&31];case 3:return Zeb[b&31]}return 0},B5=function(a){return a.B[a.row][a.u]},C5=function(a,b,c){2<=b&&1<a.u&&(--a.u,B5(a).j=0);
var d=B5(a);d.timestamp=a.D.time+0;d.j=$eb(b,c);32>a.u&&a.u++},afb=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.j=l.j;h.timestamp=l.timestamp}},D5=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},bfb=function(a){a.row=0<a.j?a.j:1;
a.u=1;D5(a,0,15)},cfb=function(a){this.B=a;
this.D=0;this.style=new x5;this.I=new z5(this.B);this.J=new z5(this.B);this.text=new z5(this.B);this.u=this.I;this.C=this.J;this.j=this.u},dfb=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.j||(A5(d,c),bfb(a.u),bfb(a.C),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.B.mode=1<<d.C;e?d.u=1:d.j!==b&&(d.j>b?(A5(d,c),D5(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},efb=function(a){a.style.set(1);
a.j=a.C;a.j.j=0;a.j.style=a.style;a.B.mode=1<<a.j.C},ffb=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.B.mode=1<<a.j.C},Oeb=function(a){this.j=a;
this.D=0;this.B=new cfb(this.j);this.I=new cfb(this.j);this.u=new y5;this.C=this.B},Seb=function(a,b,c,d){a.u.update();
b=Reb(b,c,a.u);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Bu;c=b.Kr;if(32<=e||!e)a.j.mode&a.j.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.C.j,b&96&&C5(a,0,b),c&96&&C5(a,0,c),0!==b&&0!==c&&3===a.style.type&&A5(a,d));else if(e&16)a:if(!a.u.matches(e,c)&&(b=a.u,b.Bu=e,b.Kr=c,b.state=2,b=e&8?a.I:a.B,a.C=b,a.j.mode=1<<(a.D<<2)+(b.D<<1)+(4===b.style.type?1:0),(a.j.mode|1<<(a.D<<2)+(b.D<<1)+(4!==b.style.type?1:0))&a.j.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,h=1+d-c.j;afb(c,h,f,c.j);b=f;e=c.j;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));D5(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:C5(b.j,0,32);break a;case 48:57===c?(d=b.j,B5(d).j=0,32>d.u&&d.u++):C5(b.j,1,c&15)}break;case 2:c&32&&C5(b.j,2,c&31);break;case 3:c&32&&C5(b.j,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:efb(b);
break;case 33:d=b.j;1<d.u&&(--d.u,B5(d).j=0);break;case 36:d=b.j;b=B5(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.B[a][c]===b){for(;32>=c;c++)d.B[a][c].reset();break}break;case 37:dfb(b,2,d);break;case 38:dfb(b,3,d);break;case 39:dfb(b,4,d);break;case 40:C5(b.j,0,32);break;case 41:b.style.set(2);b.j=b.u;b.j.j=0;b.j.style=b.style;b.B.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);bfb(d);ffb(b);break;case 43:ffb(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:A5(a,d)}D5(a,
0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.j&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;A5(a,d);afb(a,b,b+1,a.j-1);D5(a,a.row,1)}break;case 46:D5(b.C,0,15);break;case 47:A5(b.u,d),b.C.updateTime(b.B.time+0),d=b.C,b.C=b.u,b.u=d,efb(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,32<(d.u+=c&3)&&(d.u=32)}}},gfb=function(){},E5=function(a,b,c){this.trackData=a;
this.I=c;this.version=this.D=this.B=this.byteOffset=0;this.j=new DataView(this.trackData);this.u=[]},F5=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},G5=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},H5=function(a,b){o5.call(this);
this.B=a;this.C=b;this.track="CC3"===this.C.languageName?4:0;this.j=new Peb;this.j.u=1<<this.track},ifb=function(a){if("string"===typeof a)return!1;
a=new E5(a,8,0);return hfb(a)},hfb=function(a){if(!(a.byteOffset<a.j.byteLength)||1380139777!==G5(a))return!1;
a.version=F5(a);if(1<a.version)return!1;F5(a);F5(a);F5(a);return!0},I5=function(){o5.call(this)},jfb=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new l5(b,c,d,e.id,p.nodeValue,f||0<n,g.fd(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);jfb(a,b,c,d,e,!0,p,q,m)}}},kfb=function(a){var b=a.split(":");
a=0;b=g.v(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},lfb=function(a,b,c,d){d=Object.assign({jz:0},d);
return new m5(a,b,c,"_"+n5++,d)},J5=function(a,b){g.E.call(this);
this.F=a;this.Y=b;this.parser=null;this.j=this.F.Ey()},rfb=function(a,b,c,d,e){d=d||0;
e=e||0;if(a.j&&b){var f=e,h=mfb(a,b,d),l=[];try{for(var m=g.v(h),n=m.next();!n.done;n=m.next()){var p=n.value,q=p.trackData,t=p.xP;l="string"!==typeof q?l.concat(nfb(a,c,q,t,f)):"WEBVTT"===q.substring(0,6)?l.concat(ofb(a,q,t)):l.concat(pfb(a,c,q,t))}var w=l}catch(z){g.HD(z),a.clear(),w=[]}if(0!==w.length)return w}b=qfb(b);if(!b)return[];try{return"string"!==typeof b?nfb(a,c,b,d,e):"WEBVTT"===b.substring(0,6)?ofb(a,b,d):pfb(a,c,b,d)}catch(z){return g.HD(z),a.clear(),[]}},qfb=function(a){if("string"===
typeof a||ifb(a))return a;
var b=new DataView(a);if(8>=b.byteLength||1718909296!==b.getUint32(4))return"";b=g.pG(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.aG(a)},mfb=function(a,b,c){if("string"===typeof b||ifb(b))return[{trackData:b,
xP:c}];var d=new DataView(b);if(8>=d.byteLength||1718909296!==d.getUint32(4))return[];var e=g.$sa(d);if(a.j&&e){var f=g.Ssa(e),h=g.Tsa(e);e=e.j;f&&e&&a.j.jE(e,f,h)}a=g.yG(d,1835295092);if(!a||!a.length||!a[0].size)return[];f=[];for(h=0;h<a.length;h++)e=a[h],e=new Uint8Array(b,e.dataOffset,e.size-(e.dataOffset-e.offset)),e=g.aG(e),f.push({trackData:e,xP:c+1E3*h});sfb(d,f,c);return f=f.filter(function(l){return!!l.trackData})},sfb=function(a,b,c){var d=g.pG(a,0,1836476516),e=9E4;
d&&(e=g.qG(d)||9E4);d=0;for(var f=g.yG(a,1836019558),h=0;h<f.length;h++){var l=f[h];h<b.length&&(l=g.pG(a,l.dataOffset,1953653094))&&(l=g.pG(a,l.dataOffset,1952867444))&&(l=g.wG(l)/e*1E3,0===h&&(d=l),b[h].xP=l-d+c||c*h*1E3)}},nfb=function(a,b,c,d,e){if(!ifb(c))throw Error("Invalid binary caption track data");
a.parser||(a.parser=new H5(e,b));return a.parser.u(c,d)},ofb=function(a,b,c){a.parser||(a.parser=new I5);
a=a.parser.u(b,c);.01>Math.random()&&g.ID(Error("Deprecated subtitles format in web player: WebVTT"));return a},pfb=function(a,b,c,d){if("{"===c[0])try{return a.parser||(a.parser=new v5(tfb(b))),a.parser.u(c,d)}catch(f){return g.HD(f),[]}var e=g.L7a(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.parser||(a.parser=new p5(tfb(b),a.Y)),a.parser.u(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},tfb=function(a){var b=
{};
if(a=g.lL(a))b.lang=a,g.L9a.test(a)&&(b.di=1);return b},K5=function(a){g.tT.call(this,a);
var b=this;this.F=a;this.Y=this.F.V();this.videoData=this.F.getVideoData();this.ub=this.F.kb();this.B={Fe:{}};this.D={Fe:{}};this.Ga=[];this.Z={};this.Xa={};this.ya=!1;this.lc=g.kN(this.videoData);this.jb=g.LKa(this.videoData,this.F);this.Vb=!!this.videoData.captionTracks.length;this.Dc=!!this.videoData.Jd;this.bb="3"===this.Y.controlsType;this.j=this.J=this.T=this.Pa=this.qb=null;this.Za=new J5(this.F,this.Y);this.u=null;this.Aa=new g.XH(this);this.I=new g.V({G:"div",N:"ytp-caption-window-container",
X:{id:"ytp-caption-window-container"}});this.ea={top:0,right:0,bottom:0,left:0,width:1,height:1};var c=null,d=g.wq("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.kq(d));this.storage=c;var e;this.Ob=!(null==(e=a.ye())||!e.bE());this.C=ufb(this);this.oa=!this.C&&this.bb&&this.Ob&&this.jb;g.I(this,this.Za);this.C?this.Ma=this.Ka=null:(this.Ka=new g.Ep(this.VP,void 0,this),g.I(this,this.Ka),this.Ma=new g.Gp(this.f9,2E3,this),g.I(this,this.Ma));g.I(this,this.Aa);g.yS(this.player,this.I.element,
4);g.I(this,this.I);this.C||this.Aa.S(a,"resize",this.YP);(this.Gb=g.vK(this.Y)&&!g.Bz()&&!this.F.isFullscreen()&&!this.C&&!this.oa)&&this.Aa.S(a,"resize",this.M6);this.Aa.S(a,"onPlaybackAudioChange",this.a6);this.Aa.S(a,g.dE("captions"),function(f){b.onCueRangeEnter(f)});
this.Aa.S(a,g.eE("captions"),function(f){b.onCueRangeExit(f)});
vfb(this,leb()||{});this.player.Oa("onCaptionsModuleAvailable")},yfb=function(a){if(1===a.Y.Vb||1===a.videoData.zC||"alwayson"===g.PM(a.videoData,"yt:cc"))return!0;
if(a.videoData.captionTracks.length)var b=a.player.getAudioTrack().u;if(2===a.Y.Vb){if(g.OK(a.Y))var c=wfb(a);else if(a.storage)try{c=a.storage.get("module-enabled")}catch(e){a.storage.remove("module-enabled")}else c=null;if(null!=c)return!!c}c=deb(a.player.getAudioTrack(),g.OK(a.Y));var d=g.PM(a.videoData,"yt:cc");if(void 0===xfb(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===c)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===c)return"on"===d}else return"on"===d;return"ON"===
b||"on"===g.PM(a.videoData,"yt:cc")},L5=function(a,b){if(a.u&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.player.getAudioTrack();return!!a.j||"FORCED_ON"===a.u},xfb=function(a){var b=void 0,c=g.$z(g.Zz(),65);
if(g.OK(a.Y)&&null!=c){if(null!=wfb(a))return!1;b=!c}return b},zfb=function(a){var b;
a.lc?b=new i5(a.Y,a.videoData,a.player.getAudioTrack(),a.player):a.jb?b=new g5(a.videoData.j,a.player):a.Vb?b=new g.xT(a.Y,a.videoData,a.player.getAudioTrack()):b=new g.zT(a.Y,a.videoData.Jd,a.videoData.videoId,g.Dya(a.videoData),a.videoData.tm,a.videoData.eventId);return b},N5=function(a,b){if(a.j){if(a.J&&a.J.C)return a.J.C;
g.bN(a.videoData)&&(b=!0);b||(b=a.Dc?!1:a.Vb?!1:!0);b=b||Afb(a);b=g.uT(a.j.j,b);var c=null;if(eeb(a.Y)){var d=a.F.isInline()?void 0:g.Tz("yt-player-caption-sticky-language");for(var e=[d,a.videoData.captionsLanguagePreference,a.Y.captionsLanguagePreference,g.PM(a.videoData,"yt:cc_default_lang")],f=!1,h=0;h<e.length;h++){var l=e[h];if(l){f=!0;for(var m=0;m<b.length;m++)if(g.lL(b[m])===l)return b[m];l=l.split("-")[0];for(m=0;m<b.length;m++)if(g.lL(b[m])===l)return b[m]}}if(a.Y.K("web_player_always_enable_auto_translation")&&
f&&a.j&&(e=a.j.C,e.length))for(e=g.v(e),f=e.next();!f.done;f=e.next())if(f=f.value,f.languageCode===d){c=f;break}}else for(d=[a.videoData.captionsLanguagePreference,a.Y.captionsLanguagePreference,g.PM(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(f=0;f<b.length;f++)if(g.lL(b[f])===d[e])return b[f];d=null;a.J&&a.J.B&&(d=a.J.B);d||(d=b.find(function(n){return n.isDefault})||null);
d||(d=b[0]||M5(a));d&&c&&(d=feb(d,c));return d}return null},M5=function(a){return a.J&&a.J.j},O5=function(a){var b=M5(a);
return!!b&&a.u===b},Bfb=function(a){g.uT(a.j.j,!0);
var b=deb(a.player.getAudioTrack(),g.OK(a.Y)),c;"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=N5(a,a.ya):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&L5(a)?c=M5(a):xfb(a)||a.ya||yfb(a)?c=N5(a,a.ya):L5(a)&&(c=M5(a));if(a.C||a.oa){var d=g.uT(a.j.j,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.df("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.jL(f));h.setAttribute("srclang",g.lL(f));h.setAttribute("id",f.toString());a.oa||h.setAttribute("src",a.j.Wu(f,"vtt"));f===c&&h.setAttribute("default",
"1");b.push(h)}c=a.F.ye();c.WA(b);c=c.vb();a.Ob&&a.Aa.S(c.textTracks,"change",a.k8)}else!a.u&&c&&P5(a,c),a.player.Oa("onCaptionsTrackListChanged"),a.player.Oa("onApiChange")},Cfb=function(a,b){var c=a.F.ye().vb().textTracks;
a=a.u.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},P5=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.ya=c,a.ya&&(g.OK(a.Y)?Q5(a,!!b):R5(a,!!b)));a.u=b;L5(a)&&(a.u=M5(a));a.load()},Efb=function(a,b){if(b instanceof m5){var c=a.Z[b.id];
c&&c.u!==b&&(c.dispose(),delete a.Z[b.id],c=null);c||(c=Dfb(a,b))&&(a.Z[b.id]=c)}else c=b.windowId,a.Xa[c]||(a.Xa[c]=[]),a.Xa[c].push(b)},Dfb=function(a,b){var c=Ffb(a);
if(!c)return null;var d=a.u?g.lL(a.u):null;d&&g.L9a.test(d)&&(b.params.di=1);var e=a.ub.getPlayerSize();d=e.height*a.ea.height;e=e.width*a.ea.width;"google-live"!==a.Y.playerStyle||a.B.isDefault||Object.assign(b.params,a.B);switch(null!=b.params.jz?b.params.jz:1<b.j.length?1:0){case 1:return new j5(b,a.B,a.D,c.width,c.height,e,d,a.Y.experiments,a.iJ.bind(a),a.F);case 2:return new k5(b,a.B,a.D,c.width,c.height,e,d,a.Y.experiments,a.iJ.bind(a),a.F);default:return new h5(b,a.B,a.D,c.width,c.height,e,
d,a.Y.experiments,a.iJ.bind(a),a.F)}},vfb=function(a,b,c){c=void 0===c?!1:c;
var d=S5.Fe;a.B={};Object.assign(a.B,S5);a.B.Fe={};Object.assign(a.B.Fe,d);a.D={Fe:{}};var e=b.backgroundOverride?a.D:a.B,f=b.background||d.background;t5.test(f);e.Fe.background=f;e=b.colorOverride?a.D:a.B;f=b.color||d.color;t5.test(f);e.Fe.color=f;e=b.windowColorOverride?a.D:a.B;f=b.windowColor||S5.windowColor;t5.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.D:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Fe.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.D:a.B;f=b.fontSizeIncrement;
null==f&&(f=d.fontSizeIncrement);e.Fe.fontSizeIncrement=f;f=b.fontStyleOverride?a.D:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);f=f.Fe;switch(e){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}e=b.textOpacityOverride?a.D:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Fe.textOpacity=f;e=b.windowOpacityOverride?a.D:a.B;f=b.windowOpacity;null==f&&(f=S5.windowOpacity);e.windowOpacity=
f;e=b.charEdgeStyleOverride?a.D:a.B;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Fe.charEdgeStyle=f;e=b.fontFamilyOverride?a.D:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Fe.fontFamily=f;a.loaded&&a.YP();c&&g.Sz("yt-player-caption-display-settings",b,2592E3)},Hfb=function(a,b,c){b&&!a.T?(b=Heb({di:0,
lang:"en-GB"}),a.T=[b,new l5(b.start,b.end-b.start,0,b.id,null!=c?c:"Captions look like this")],a.player.De(a.T)):!b&&a.T&&(Gfb(a,a.T),a.T=null)},Gfb=function(a,b){a.player.Dh(b);
b=g.v(b);for(var c=b.next();!c.done;c=b.next())g.Ab(a.Ga,c.value);g.Fp(a.Ka)},Ffb=function(a){var b=a.ub.getVideoContentRect(!0).height,c=a.ub.getVideoContentRect(!0).width;
if(!b||!c)return null;b*=a.ea.height;c*=a.ea.width;return{width:c,height:b}},R5=function(a,b){if(a.storage)try{a.storage.set("module-enabled",b)}catch(c){}},Q5=function(a,b){a.F.isInline()||g.Sz("yt-player-sticky-caption",b,2592E3)},wfb=function(a){if(!a.F.isInline())return g.Tz("yt-player-sticky-caption")},ufb=function(a){var b,c=!(null==(b=a.F.ye())||!b.aE());
return a.bb&&c&&!a.jb},Afb=function(a){return a.Y.K("web_deprecate_always_includes_asr_setting")&&g.OK(a.Y)?!0:!!g.$z(g.Zz(),66)};
g.vW.prototype.JB=g.ba(40,function(a){var b=2;this.bb.has(a)?b=0:g.KQa(this,a)&&(b=1);return b});
g.uY.prototype.JB=g.ba(39,function(a){return this.md.JB(a)});
g.vW.prototype.jE=g.ba(38,function(a,b,c){this.Ka.set(a,{Tr:b,TA:c})});
g.uY.prototype.jE=g.ba(37,function(a,b,c){this.md.jE(a,b,c)});
g.wT.prototype.zO=g.ba(30,function(){return!1});
g.wT.prototype.Us=g.ba(29,function(){});
g.xT.prototype.Us=g.ba(28,function(a,b,c){var d=this;this.isDisposed();b=this.Wu(a,b);this.rr();this.u=g.Ky(b,{format:"RAW",onSuccess:function(e){d.u=null;c(e.responseText,a)},
withCredentials:!0})});
g.zT.prototype.Us=g.ba(27,function(a,b,c){var d=this;this.isDisposed();b=this.Wu(a,b);this.rr();this.u=g.Ky(b,{format:"RAW",onSuccess:function(e){d.u=null;c(e.responseText,a)},
withCredentials:!0})});
g.gT.prototype.Ux=g.ba(26,function(){for(var a=g.Re(document,"track",void 0,this.j),b=0;b<a.length;b++)g.jf(a[b])});
g.jW.prototype.Ux=g.ba(25,function(){this.mediaElement.Ux()});
g.gT.prototype.bE=g.ba(24,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.jW.prototype.bE=g.ba(23,function(){return this.mediaElement.bE()});
g.gT.prototype.aE=g.ba(22,function(){return!!this.j.textTracks});
g.jW.prototype.aE=g.ba(21,function(){return this.mediaElement.aE()});
g.gT.prototype.WA=g.ba(20,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.jW.prototype.WA=g.ba(19,function(a){this.mediaElement.WA(a)});
g.oY.prototype.ZB=g.ba(9,function(){return this.I});
g.xZ.prototype.ZB=g.ba(8,function(){var a;return(null==(a=g.hS(this))?void 0:a.Ey())||null});
g.rS.prototype.Ey=g.ba(7,function(){return this.app.ZB()});
g.lZ.prototype.Ey=g.ba(6,function(){var a;return(null==(a=this.Fa)?void 0:a.ZB())||null});
g.PF.prototype.eG=g.ba(2,function(a){return(a=this.Go(a))?a.j:0});
g.EH.prototype.eG=g.ba(1,function(){return 0});
var jeb=/#(.)(.)(.)/,ieb=/^#(?:[0-9a-f]{3}){1,2}$/i,qeb={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",
chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",
li:"Limburgish",lkt:"Lakota",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaq",
min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",
nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",
pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",
sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",
sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",
ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",
ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",
za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};f5.prototype.contains=function(a){a=g.Ob(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
f5.prototype.length=function(){return this.segments.length/2};
g.x(neb,g.E);g.k=neb.prototype;g.k.qa=function(){g.E.prototype.qa.call(this);this.B&&this.B.cancel()};
g.k.rz=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Gd();var b=this.j;this.j=g.qb(this.ea.aq(a).ib);b!==this.j&&this.T&&this.T()};
g.k.reset=function(){this.C=new f5;this.I=-1;this.B&&(this.B.cancel(),this.B=null)};
g.k.rV=function(){this.isDisposed();var a;if(a=null!=this.j)a=this.j,a=a.j.Er(a);if(a&&!this.B&&!(this.j&&30<this.j.startTime-this.player.getCurrentTime())){a=this.j;a=a.j.KA(a);var b;if(null==(b=this.player.getVideoData())?0:b.enableServerStitchedDai)if(b=this.player.Ey()){var c=a.ib[0].j.info.id,d=a.ib[0].Na,e=a.ib[0].C;if(this.policy.Aa){if(b=b.Gs(e,d,c,3))a.J=b}else if(c=b.Mm(e,d,c,3))if(b=b.JB(d),0===b)c&&(a.u=new g.IF(c));else if(2===b){this.J.start();oeb(this)&&this.seekTo(this.player.getCurrentTime());
return}}a.ib[0].duration?(this.C.contains(a.ib[0].Na)||peb(this,a),this.j=g.qb(a.ib)):oeb(this)&&this.seekTo(this.player.getCurrentTime())}this.J.start()};
g.x(g5,g.wT);g.k=g5.prototype;g.k.Us=function(a,b,c){var d=this;this.rr();b=seb(this,a.getId());b||(b=a.languageCode,b=this.u.isManifestless?teb(this,b,"386"):teb(this,b));if(b){var e=1E3*(b.index.eG(b.index.Om())-b.index.getStartTime(b.index.Om())),f=new g.rKa(this.Y);this.B=new neb(f,this.F,b,function(h,l){c(h,a,l,e)},this.I||g.AH(b.info),function(){d.B&&d.B.reset();
d.D=!0})}};
g.k.zO=function(){var a=this.D;this.D=!1;return a};
g.k.Zy=function(a){var b=this.I?[new g.iL({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.iL({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.u.isManifestless?reb(this,"386"):reb(this);b=g.v(b);for(var c=b.next();!c.done;c=b.next())g.vT(this.j,c.value);a()};
g.k.rr=function(){this.B&&(this.B.dispose(),this.B=null)};
g.k.Wu=function(){return""};
var t5=/^#(?:[0-9a-f]{3}){1,2}$/i,ueb=window.yt&&window.yt.msgs_||window.ytcfg&&window.ytcfg.msgs||{};g.Ka("yt.msgs_",ueb);var yeb=["left","right","center","justify"];g.x(h5,g.V);g.k=h5.prototype;g.k.YZ=function(a,b){this.qb=a;this.ub=b;var c=g.Ym(this.element,this.element.parentElement);this.Gb=a-c.x;this.Vb=b-c.y};
g.k.XZ=function(a,b){if(a!==this.qb||b!==this.ub){g.Np(this.element,"ytp-dragging")||g.Op(this.element,"ytp-dragging");var c=g.$m(this.element);a=a-this.Gb-.02*this.playerWidth;var d=b-this.Vb-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.pe(e,0,2));var f=(d+c.height/2)/this.Za*3;f=Math.floor(g.pe(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.pe(a,0,1);c=(d+f/2*c.height)/this.Za;c=100*g.pe(c,0,1);this.u.params.Cl=b;this.u.params.Hn=c;this.u.params.Kj=a;this.u.params.isDefault=
!1;this.j.Cl=b;this.j.Hn=c;this.j.Kj=a;this.j.isDefault=!1;this.ya.Cl=b;this.ya.Hn=c;this.ya.Kj=a;this.ya.isDefault=!1;this.tX()}};
g.k.WZ=function(){g.Qp(this.element,"ytp-dragging")};
g.k.tX=function(){this.Tz(this.I)};
g.k.getType=function(){return this.type};
g.k.Tz=function(a){var b=Math.min(this.QT(),this.maxWidth),c=this.PT(),d="";3===this.u.params.di&&(d="rotate(180deg)");g.Pm(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.tK(a);d={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.j.Kj+2,f=this.j.Cl;switch(f){case 0:case 3:case 6:(b=this.j.Fe.fontSizeIncrement)&&0<b&&2!==this.j.di&&3!==
this.j.di&&(e=Math.max(e/(1+2*b),2));d.left=e+"%";break;case 1:case 4:case 7:d.left=e+"%";e=this.C.offsetWidth;b||e?(b=b||e+1,d.width=b+"px",d["margin-left"]=b/-2+"px"):d.transform+=" translateX(-50%)";break;case 2:case 5:case 8:d.right=100-e+"%"}b=.96*this.j.Hn+2;switch(f){case 0:case 1:case 2:d.top=b+"%";break;case 3:case 4:case 5:d.top=b+"%";(c=c||this.element.clientHeight)?(d.height=c+"px",d["margin-top"]=c/-2+"px"):d.transform+=" translateY(-50%)";break;case 6:case 7:case 8:d.bottom=100-b+"%"}g.Pm(this.element,
d);if(this.D){c=this.C.offsetHeight;d=1;for(f=0;f<a.length;f++)b=a[f],"string"===typeof b.text&&(d+=b.text.split("\n").length-1,b.append||0===f||d++);c/=d;this.D.style.height=c+"px";this.D.style.width=c+"px";this.element.style.paddingLeft=c+5+"px";this.element.style.paddingRight=c+5+"px";a=Number(this.element.style.marginLeft.replace("px",""))-c-5;c=Number(this.element.style.marginRight.replace("px",""))-c-5;this.element.style.marginLeft=a+"px";this.element.style.marginRight=c+"px"}};
g.k.tK=function(a){var b;for(b=0;b<a.length&&a[b]===this.I[b];b++);if(this.Ga||this.I.length>b)b=0,this.Ga=!1,this.I=[],this.J=this.Ma=this.Ka=null,g.gf(this.C);for(;b<a.length;b++)Deb(this,a[b])};
g.k.QT=function(){return 0};
g.k.PT=function(){return 0};
g.k.toString=function(){return g.V.prototype.toString.call(this)};g.x(i5,g.wT);i5.prototype.Us=function(a,b,c){heb(this.videoData.videoId,a.vssId,c)};
i5.prototype.Zy=function(a){if(this.audioTrack)for(var b=g.v(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.vT(this.j,c.value);a()};g.x(j5,h5);j5.prototype.tK=function(a){var b=this.u.j;h5.prototype.tK.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,Ifb);var e=c.j;var f=d}Deb(this,c,d)}};
var Ifb={E4:!0};g.x(k5,h5);g.k=k5.prototype;g.k.tX=function(){g.Ip(this.bb)};
g.k.C7=function(){g.Qp(this.element,"ytp-rollup-mode");this.Tz(this.Ic,!0)};
g.k.PT=function(){return this.B?this.oa:this.Z};
g.k.QT=function(){return this.B?this.Z:this.oa};
g.k.Tz=function(a,b){this.Ic=a;if(this.u.params.Sq){for(var c=0,d=0;d<this.I.length&&c<a.length;d++)this.I[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.I.concat(a.slice(c)));this.lc=this.oa;this.Z=this.oa=0;h5.prototype.Tz.call(this,a);Geb(this,b)}h5.prototype.Tz.call(this,a)};g.x(l5,g.bE);l5.prototype.toString=function(){return g.bE.prototype.toString.call(this)};g.x(m5,g.bE);m5.prototype.toString=function(){return g.bE.prototype.toString.call(this)};
var n5=0;g.x(o5,g.E);o5.prototype.u=function(){return[]};
o5.prototype.reset=function(){};g.x(p5,o5);p5.prototype.reset=function(){this.J={};this.B=this.j=null;this.I=!0};
p5.prototype.u=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.v(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.v(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=r5(a,"b");
null!=l&&(h.bold=l);l=r5(a,"i");null!=l&&(h.italic=l);l=r5(a,"u");null!=l&&(h.underline=l);l=s5(a,"et");null!=l&&(h.charEdgeStyle=l);l=s5(a,"of");null!=l&&(h.offset=l);l=u5(a,"bc");null!=l&&(h.background=l);l=u5(a,"ec");null!=l&&(h.NK=l);l=u5(a,"fc");null!=l&&(h.color=l);l=s5(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=q5(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=q5(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=q5(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=s5(a,"rb");null!=l&&10!==l&&
0!==l&&(h.Rf=10<l?l-1:l);a=s5(a,"hg");null!=a&&(h.IU=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.ea[c]=Keb(this,a);break;case "wp":c=a.getAttribute("id"),this.T[c]=Leb(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.v(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.j=Meb(this,a,b,!1);(a=this.J[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.J[this.j.id]=this.j;d.push(this.j);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.D;
h=!!r5(a,"a");l=(q5(a,"t")||0)+l;var m=q5(a,"d")||5E3;h||(!this.I&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&"\n"===this.B.text&&(this.B.text=""));var n=h?6:5,p=a.getAttribute("p");p=p?this.pens[p]:null;var q=Array.from(a.childNodes);q.length&&(this.I=null!=a.getAttribute("d"));for(var t=0;t<q.length;t++){var w=q[t],z=void 0;0<t&&(h=!0);var C=void 0;1===w.nodeType&&(C=w);if(C&&"s"===C.tagName){if((w=(w=C.getAttribute("p"))?this.pens[w]:null)&&w.Rf&&(1===w.Rf?(w=q.slice(t,t+
4),4===w.length&&(z=Jeb(l,m,f,h,n,w,this.pens),t+=3)):z=Jeb(l,m,f,h,n,[C],this.pens)),!z){var G=C;z=l;C=m;w=f;var O=h,N=n,K=G.textContent?G.textContent:"",W=G.getAttribute("p");W=W?this.pens[W]:null;G=q5(G,"t")||0;z=new l5(z+G,C-G,N,w,K,O,W)}}else z=new l5(l,m,n,f,w.textContent||"",h,p);c.push(z);this.B=z}if(0<c.length)for(c[0].windowId===this.D&&(this.j=Meb(this,a,b,!0),d.push(this.j)),a=g.v(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];
return b};var Jfb=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.x(v5,o5);v5.prototype.reset=function(){this.B.clear()};
v5.prototype.u=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.v(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.j.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.italic=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.NK=w5(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=w5(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=w5(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.Rf=10<h?h-1:h,f.Gn=Jfb.get(f.Rf));e.hgHorizGroup&&(f.IU=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.v(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.D.get(h)):Object.assign(f,
this.I),void 0!==e.mhModeHint&&(f.jz=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.di=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.GP=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=w5(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.D.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.v(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.C.get(h)),void 0!==e.ahHorPos&&
(f.Kj=e.ahHorPos),void 0!==e.apPoint&&(f.Cl=e.apPoint),void 0!==e.avVerPos&&(f.Hn=e.avVerPos),void 0!==e.ccCols&&(f.Or=e.ccCols),void 0!==e.rcRows&&(f.Sq=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.v(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=Neb(this,l,d,e,f),a.push(d),this.B.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+n5++,h=Neb(this,l,d,e,f),a.push(h),this.B.set(f,h));0===e&&(e=5E3);h=this.B.get(f);var m=
!!l.aAppend,n=m?6:5,p=l.segs,q=null;l.pPenId&&(q=this.j.get(l.pPenId));for(l=0;l<p.length;l++){var t=p[l],w=t.utf8;if(w){var z=t.tOffsetMs||0,C=null;t.pPenId&&(C=this.j.get(t.pPenId));if(2===(null!=h.params.jz?h.params.jz:1<h.j.length?1:0)&&m&&"\n"===w)continue;if(t=C&&1===C.Rf)if(t=l,t+3>=p.length||!p[t+1].pPenId||!p[t+2].pPenId||!p[t+3].pPenId)t=!1;else{var G=p[t+1].pPenId;(G=this.j.get(G))&&G.Rf&&2===G.Rf?(G=p[t+2].pPenId,G=this.j.get(G),!G||!G.Rf||3>G.Rf?t=!1:(G=p[t+3].pPenId,t=(G=this.j.get(G))&&
G.Rf&&2===G.Rf?!0:!1)):t=!1}if(t){z=p[l+1].utf8;t=p[l+3].utf8;G=p[l+2].utf8;var O=this.j.get(p[l+2].pPenId);w=Ieb(w,z,G,t,O);m=new l5(d,e,n,f,w,m,C);l+=3}else m=new l5(d+z,e-z,n,h.id,w,m,C||q);m&&(a.push(m),h.j.push(m))}m=!0}}}b=a}else b=[];return b};Peb.prototype.clear=function(){this.B=this.time=this.mode=0;this.j=[];this.reset()};
Peb.prototype.reset=function(){this.mode=0;this.C.reset(0);this.D.reset(1)};
var Qeb=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];x5.prototype.set=function(a){this.type=a};
x5.prototype.get=function(){return this.type};
y5.prototype.clear=function(){this.state=0};
y5.prototype.update=function(){this.state=2===this.state?1:0};
y5.prototype.Ge=function(){return 0!==this.state};
y5.prototype.matches=function(a,b){return this.Ge()&&a===this.Bu&&b===this.Kr};
Veb.prototype.reset=function(){this.timestamp=this.j=0};
z5.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.B[b][c].timestamp=a};
z5.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0===d.j?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
z5.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.j=0;this.u=this.row=1};
var Web=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Xeb=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Yeb=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Zeb=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];cfb.prototype.reset=function(a,b){this.D=b;this.style.set(2);this.u=this.I;this.C=this.J;this.j=this.u;var c=(a<<2)+(b<<1);this.I.reset(c);this.J.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
Oeb.prototype.reset=function(a){this.D=a;this.u.clear();this.C=this.B;this.B.reset(a,0);this.I.reset(a,1)};gfb.prototype.C=function(){};g.x(E5,gfb);E5.prototype.C=function(a,b,c,d,e){if(c<d){var f="_"+n5++;c=c/1E3-this.I;d=d/1E3-this.I;a=new m5(c,d-c,5,f,{textAlign:0,Cl:0,Kj:2.5*b,Hn:5.33*a});e=new l5(c,d-c,5,f,e);this.u.push(a);this.u.push(e)}};
g.x(H5,o5);H5.prototype.u=function(a){a=new E5(a,a.byteLength,this.B);if(hfb(a)){for(;a.byteOffset<a.j.byteLength;)for(0===a.version?a.B=G5(a)*(1E3/45):1===a.version&&(a.B=4294967296*G5(a)+G5(a)),a.D=F5(a);0<a.D;a.D--){var b=F5(a),c=F5(a),d=F5(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.j,b.j.push({time:a.B,type:this.track,RS:c,SS:d,order:b.j.length}))}Ueb(this.j,a);return a.u}return[]};
H5.prototype.reset=function(){this.j.clear()};g.x(I5,o5);
I5.prototype.u=function(a,b){var c=[];a=a.split(Kfb);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!Lfb.test(e)){var h=Mfb.exec(e);if(h&&4<=h.length){var l=kfb(h[1]),m=kfb(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var t=null,w="";n=g.v(n);for(var z=n.next();!z.done;z=n.next())if(z=z.value.split(":"),2===z.length){var C=z[1];switch(z[0]){case "line":z=C.split(",");z[0].endsWith("%")&&(p=z[0],h.Hn=Number.parseInt(p,10),2===z.length&&(q=z[1].trim()));break;case "position":z=
C.split(",");t=z[0];h.Kj=Number.parseInt(t,10);2===z.length&&(w=z[1].trim());break;case "align":switch(C){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!t)switch(h.textAlign){case 0:h.Kj=0;break;case 1:h.Kj=100;break;case 2:h.Kj=50}if(null!=h.textAlign){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(w){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=0>p||8<p?7:p;h.Cl=q}e=e.substring(Mfb.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");w=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=lfb(l,m,5,w),m=new l5(l,m,5,f.id,h,!1,g.fd(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=h.split(Nfb),1===q.length?(h=5,w=lfb(l,m,h,w)):(p=h=6,w=Object.assign({Or:32},w),w=new m5(l,m,p,"_"+n5++,w)),c.push(w),p=l,t=0;t<q.length;t++)n=q[t],0===t%2?(z=g.L7a("<html>"+n+"</html>"),z.getElementsByTagName("parsererror").length?
(C=z.createElement("span"),C.appendChild(z.createTextNode(n))):C=z.firstChild,jfb(this,p,m-(p-l),h,w,0<t,C,e,c)):p=kfb(n)+f}Mfb.lastIndex=0}}return c};
var Lfb=/^NOTE/,Kfb=/(?:\r\n|\r|\n){2,}/,Mfb=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Nfb=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.kW.ev(I5,{u:"wvppt"});g.x(J5,g.E);J5.prototype.clear=function(){this.parser&&this.parser.dispose();this.parser=null};
J5.prototype.reset=function(){this.parser&&this.parser.reset()};
J5.prototype.qa=function(){g.E.prototype.qa.call(this);this.clear()};var S5={windowColor:"#080808",windowOpacity:0,textAlign:2,Cl:7,Kj:50,Hn:100,isDefault:!0,Fe:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.x(K5,g.tT);g.k=K5.prototype;g.k.qa=function(){if(this.C||this.oa){var a=this.F.ye();a&&!a.isDisposed()&&a.Ux()}else Hfb(this,!1);g.tT.prototype.qa.call(this)};
g.k.lw=function(){if(this.bb)return this.C||this.oa;var a=this.player.getAudioTrack();if(this.Y.K("html5_honor_caption_availabilities_in_audio_track")&&!a.captionTracks.length)return!1;a=deb(a,g.OK(this.Y));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?L5(this):xfb(this)||L5(this)?!0:yfb(this)};
g.k.load=function(){var a=this;g.tT.prototype.load.call(this);this.J=this.player.getAudioTrack();this.j?this.u&&(this.Za.clear(),this.C?Cfb(this,!0):3!==this.player.getPresentingPlayerType()&&this.j.Us(this.u,"json3",function(b,c,d,e){b&&(a.Y.K("html5_modify_caption_vss_logging")&&(a.videoData.Ow=a.u||void 0),a.j.zO()&&(a.Ga=[],a.F.jf("captions"),g.Fp(a.Ka),a.Za.reset()),b=rfb(a.Za,b,c,d,e),a.player.De(b,void 0,a.jb),!a.ya||a.oa||O5(a)||g.EK(a.Y)||g.xK(a.Y)||g.yK(a.Y)||"shortspage"===a.Y.Ka||a.player.isInline()||
(g.Jp(a.Ma),b=Heb({Cl:0,Kj:5,Hn:5,Sq:2,textAlign:0,di:0,lang:"en-GB"}),a.Pa=[b],c=["Click "," for settings"],a.qb||(d=new g.oQ(g.GQ()),g.I(a,d),a.qb=d.element),d=b.end-b.start,(e=g.jL(a.u))&&a.Pa.push(new l5(b.start,d,0,b.id,e)),a.Pa.push(new l5(b.start,d,0,b.id,c[0]),new l5(b.start,d,0,b.id,a.qb,!0),new l5(b.start,d,0,b.id,c[1],!0)),a.player.De(a.Pa),g.Hp(a.Ma)),!a.ya||a.oa||O5(a)||(g.OK(a.Y)?Q5(a,!0):R5(a,!0),a.J&&(a.J.C=a.u),a.player.wr()),a.ya=!1)}),this.C||this.oa||O5(this)||this.player.Oa("captionschanged",
g.kL(this.u))):(this.j=zfb(this),g.I(this,this.j),this.j.Zy(function(){Bfb(a)}))};
g.k.unload=function(){this.C&&this.u?Cfb(this,!1):(this.Ma&&g.Jp(this.Ma),this.player.jf("captions"),this.Ga=[],this.j&&this.j.rr(),this.Za.clear(),this.T&&this.player.De(this.T),this.YP());g.tT.prototype.unload.call(this);this.player.wr();this.player.Oa("captionschanged",{})};
g.k.create=function(){this.lw()&&this.load();var a;a:{var b,c,d;if(this.Y.K("suggest_caption_correction_menu_item")&&this.Y.K("web_player_nitrate_promo_tooltip")&&(null==(b=this.videoData.getPlayerResponse())?0:null==(c=b.captions)?0:null==(d=c.playerCaptionsTracklistRenderer)?0:d.openTranscriptCommand)){var e,f;if(b=null==(a=this.videoData.getPlayerResponse())?void 0:null==(e=a.captions)?void 0:null==(f=e.playerCaptionsTracklistRenderer)?void 0:f.captionTracks)for(a=g.v(b),e=a.next();!e.done;e=a.next())if(e=
e.value,"asr"===e.kind&&"en"===e.languageCode){a=!0;break a}}a=!1}a&&this.F.ma("showpromotooltip",this.I.element)};
g.k.k8=function(){for(var a=this.F.ye().vb().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;for(var d=g.uT(this.j.j,!0),e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.u:null)!==b&&P5(this,b,!0)};
g.k.l$=function(){!this.u&&this.C||this.unload()};
g.k.onCueRangeEnter=function(a){this.Ga.push(a);g.Fp(this.Ka)};
g.k.onCueRangeExit=function(a){g.Ab(this.Ga,a);this.j instanceof g5&&this.j.I&&this.player.Dh([a]);g.Fp(this.Ka)};
g.k.getCaptionWindowContainerId=function(){return this.I.element.id};
g.k.f9=function(){Gfb(this,this.Pa);this.Pa=null};
g.k.VP=function(){var a=this;if(!this.Gb||!this.C){this.Ka.stop();g.gba(this.Xa);this.Ga.sort(g.cE);var b=this.Ga;if(this.T){var c=g.Un(b,function(f){return-1===this.T.indexOf(f)},this);
c.length&&(b=c)}b=g.v(b);for(c=b.next();!c.done;c=b.next())Efb(this,c.value);b={};c=g.v(Object.entries(this.Z));for(var d=c.next();!d.done;b={Yt:b.Yt,pm:b.pm},d=c.next()){var e=g.v(d.value);d=e.next().value;e=e.next().value;b.Yt=d;b.pm=e;this.Xa[b.Yt]?(b.pm.element.parentNode||(b.pm instanceof k5||b.pm instanceof j5||g.Yc(this.Z,function(f){return function(h,l){l!==f.Yt&&h.u.params.Cl===f.pm.u.params.Cl&&h.u.params.Kj===f.pm.u.params.Kj&&h.u.params.Hn===f.pm.u.params.Hn&&(h.dispose(),delete a.Z[l]);
return l===f.Yt}}(b),this),this.I.element.appendChild(b.pm.element)),b.pm.Tz(this.Xa[b.Yt])):(b.pm.dispose(),delete this.Z[b.Yt])}}};
g.k.k9=function(){vfb(this,{},!0);this.player.Oa("captionssettingschanged")};
g.k.W3=function(){var a=S5.Fe;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:S5.windowColor,windowOpacity:S5.windowOpacity};var b=leb()||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&(a.backgroundOpacity=
b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&(a.fontSizeIncrement=
b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);null!=b.windowOpacity&&
(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.OY=function(a,b){var c={};Object.assign(c,leb());Object.assign(c,a);vfb(this,c,b);this.player.Oa("captionssettingschanged")};
g.k.YP=function(){!this.C&&this.loaded&&(g.Vc(this.Z,function(a,b){a.dispose();delete this.Z[b]},this),this.VP())};
g.k.rh=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.pe(b,-2,4);this.OY({fontSizeIncrement:c});return c;case "reload":b&&!this.C&&P5(this,this.u,!0);break;case "stickyLoading":void 0!==b&&this.Y.I&&(g.OK(this.Y)?Q5(this,!!b):R5(this,!!b));break;case "track":if(!this.j)return{};if(b){if(this.C)break;if(!g.Pa(b))break;if(g.fd(b)){P5(this,null,!0);break}a=g.uT(this.j.j,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&(e.languageName!==b.languageName||
this.Y.K("html5_enable_caption_changes_for_mosaic")&&(e.captionId||"")!==(b.captionId||""))||(c=b.translationLanguage?feb(e,b.translationLanguage):e)}this.xI(b.position);!c||c===this.u&&this.loaded||(a=g.fJ(),b=g.lL(c),a.length&&b===a[a.length-1]||(a.push(b),g.Sz("yt-player-caption-language-preferences",a)),(a=eeb(this.Y))&&!this.F.isInline()&&g.Sz("yt-player-caption-sticky-language",b,86400*a),P5(this,c,!0))}else return this.loaded&&this.u&&!O5(this)?g.kL(this.u):{};return"";case "tracklist":return this.j?
g.fm(g.uT(this.j.j,!(!b||!b.includeAsr)),function(f){return g.kL(f)}):[];
case "translationLanguages":return this.j?this.j.C.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.C||void 0===b||Hfb(this,!!b);break;case "sampleSubtitlesCustomized":this.C||Hfb(this,!!b,b);break;case "recommendedTranslationLanguages":return g.fJ()}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.Y.I&&a.push("stickyLoading");return a};
g.k.cq=function(){var a=this.u;this.Y.K("html5_modify_caption_vss_logging")&&(a=this.videoData.Ow||null);if(a){var b=a.vssId;a.translationLanguage&&b&&(b="t"+b+"."+g.lL(a));return{cc:b}}return{}};
g.k.Z9=function(){this.isSubtitlesOn()?(g.OK(this.Y)?Q5(this,!1):R5(this,!1),this.Y.K("html5_modify_caption_vss_logging")&&(this.videoData.Ow=void 0),this.unload(),L5(this,!0)&&P5(this,M5(this),!1)):this.rY()};
g.k.rY=function(){this.isSubtitlesOn()||P5(this,O5(this)||!this.u?N5(this,!0):this.u,!0)};
g.k.isSubtitlesOn=function(){return!!this.loaded&&!!this.u&&!O5(this)};
g.k.a6=function(){var a=O5(this);L5(this,a)?P5(this,this.player.getAudioTrack().j,!1):this.videoData.captionTracks.length&&(this.loaded&&(this.unload(),this.Y.K("html5_honor_caption_availabilities_in_audio_track")&&(this.u=null,this.j&&(this.j.dispose(),this.j=null))),this.lw()&&(a?P5(this,N5(this),!1):this.load()))};
g.k.xI=function(a){a&&(this.ea={top:a.top,right:a.right,bottom:a.bottom,left:a.left,width:1-a.left-a.right,height:1-a.top-a.bottom},this.I.element.style.top=100*this.ea.top+"%",this.I.element.style.left=100*this.ea.left+"%",this.I.element.style.width=100*this.ea.width+"%",this.I.element.style.height=100*this.ea.height+"%",this.Y.K("html5_enable_caption_changes_for_mosaic")&&(this.I.element.style.position="absolute",a=Ffb(this)))&&(this.I.element.style.width=a.width+"px",this.I.element.style.height=
a.height+"px")};
g.k.M6=function(){var a=this.F.ye();a&&!a.isDisposed()&&a.Ux();this.F.isFullscreen()?(this.C=this.bb=!0,this.loaded&&Bfb(this)):(this.bb="3"===this.Y.controlsType,this.C=ufb(this));P5(this,this.u)};
g.k.iJ=function(){var a,b,c,d=null==(a=this.videoData.getPlayerResponse())?void 0:null==(b=a.captions)?void 0:null==(c=b.playerCaptionsTracklistRenderer)?void 0:c.openTranscriptCommand;d&&this.player.Oa("innertubeCommand",d)};
g.kW.ev(K5,{VP:"smucd"});g.sT("captions",K5);})(_yt_player);
