(function(g){var window=this;'use strict';var ghb=function(a){g.V.call(this,{G:"div",N:"ytp-inline-preview-ui"});this.dg=!1;this.player=a;this.S(a,"onStateChange",this.zP);this.S(a,"videodatachange",this.Aw);this.S(a,"onInlinePreviewModeChange",this.J4);this.mf=new g.Ep(this.Hv,null,this);g.I(this,this.mf)},y6=function(a){g.tT.call(this,a);
this.j=new ghb(this.player);g.I(this,this.j);this.j.hide();g.yS(this.player,this.j.element,4);a.isInline()&&(this.load(),a=a.getRootNode(),g.Pp(a,["ytp-inline-preview-mode","ytp-no-contextmenu"]))};
g.x(ghb,g.V);g.k=ghb.prototype;
g.k.AM=function(){this.tooltip=new g.SV(this.player,this);g.I(this,this.tooltip);g.yS(this.player,this.tooltip.element,4);this.tooltip.scale=.6;this.Qc=new g.bU(this.player);g.I(this,this.Qc);this.Wj=new g.V({G:"div",Ja:["ytp-inline-preview-scrim"]});g.I(this,this.Wj);this.Wj.Ea(this.element);this.S(this.Wj.element,"click",this.gH);this.sj=new g.LV(this.player,this,300);g.I(this,this.sj);this.sj.Ea(this.Wj.element);this.controls=new g.V({G:"div",N:"ytp-inline-preview-controls"});g.I(this,this.controls);
this.controls.Ea(this.element);var a=new g.bV(this.player,this,this.player.V().K("kevlar_simp_remove_min_width_for_mute_button"));g.I(this,a);a.Ea(this.controls.element);a=new g.JV(this.player,this);g.I(this,a);a.Ea(this.controls.element);this.Lc=new g.iV(this.player,this);g.I(this,this.Lc);g.yS(this.player,this.Lc.element,4);this.S(this.player,"appresize",this.Eb);this.S(this.player,"fullscreentoggled",this.Eb);this.Eb()};
g.k.show=function(){g.Fp(this.mf);this.dg||(this.AM(),this.dg=!0);0!==this.player.getPlayerState()&&g.V.prototype.show.call(this);this.Lc.show();this.player.Oa("onInlinePreviewUiReady")};
g.k.hide=function(){this.mf.stop();g.V.prototype.hide.call(this);this.player.isInline()||this.dg&&this.Lc.hide()};
g.k.qa=function(){g.V.prototype.qa.call(this)};
g.k.gH=function(a){a.target===this.Wj.element&&this.player.Oa("onExpandInlinePreview",a)};
g.k.J4=function(){g.Sp(this.player.getRootNode(),"ytp-inline-preview-mode",this.player.isInline())};
g.k.Le=function(){this.Lc.zc();this.sj.zc()};
g.k.Hv=function(){this.Le();g.Fp(this.mf)};
g.k.Eb=function(){g.uV(this.Lc,0,this.player.kb().getPlayerSize().width,!1);g.jV(this.Lc)};
g.k.zP=function(a){this.player.isInline()&&(0===a?this.hide():this.show())};
g.k.Aw=function(a,b){if(this.player.isInline()){g.Sp(this.player.getRootNode(),"ytp-show-inline-preview-audio-controls",b.bJ);var c,d,e;a=!(null==(e=null==(c=b.getPlayerResponse())?void 0:null==(d=c.playerConfig)?void 0:d.inlinePlaybackConfig)||!e.showScrubbingControls);g.Sp(this.player.getRootNode(),"ytp-hide-inline-preview-progress-bar",!a)}};
g.k.Jc=function(){return this.tooltip};
g.k.zg=function(){return!1};
g.k.Xg=function(){return!1};
g.k.Ub=function(){return!1};
g.k.Sl=function(){return!1};
g.k.cI=function(){};
g.k.Pp=function(){};
g.k.qy=function(){};
g.k.Qm=function(){return null};
g.k.QF=function(){return null};
g.k.SL=function(){return new g.xe(0,0)};
g.k.Ck=function(){return new g.Mm(0,0,0,0)};
g.k.handleGlobalKeyDown=function(){return!1};
g.k.handleGlobalKeyUp=function(){return!1};
g.k.Tv=function(a,b,c,d,e){var f=d=0,h=0,l=g.$m(a);if(b){c=g.Np(b,"ytp-mute-button");var m=g.Np(b,"ytp-subtitles-button"),n=g.Ym(b,this.element);b=g.$m(b);d=n.y+40;if(m||c)h=n.x-l.width+b.width}else h=c-l.width/2,f=35;b=this.player.kb().getPlayerSize().width;h=g.pe(h,0,b-l.width);d?(a.style.top=d+(e||0)+"px",a.style.bottom=""):(a.style.top="",a.style.bottom=f+"px");a.style.left=h+"px"};
g.k.showControls=function(){};
g.k.vp=function(){};
g.k.Kl=function(){return!1};
g.k.RD=function(){};
g.k.Pz=function(){};
g.k.Xq=function(){};
g.k.Wq=function(){};
g.k.VA=function(){};
g.k.Yr=function(){};
g.k.DD=function(){};g.x(y6,g.tT);y6.prototype.Vk=function(){return!1};
y6.prototype.load=function(){this.player.hideControls();this.j.show()};
y6.prototype.unload=function(){this.player.showControls();this.j.hide()};g.sT("inline_preview",y6);})(_yt_player);
